# Generated by Django 5.2.13 on 2026-04-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date',), 'verbose_name': 'Liveact', 'verbose_name_plural': 'Liveacts'},
        ),
    ]
