# Generated by Django 5.2.13 on 2026-04-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_participant_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.SlugField(blank=True),
        ),
    ]
