# Generated by Django 5.2.13 on 2026-04-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_participant_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(help_text='email muss be unique', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(help_text='max 100 letters allows', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(help_text='max 100 letters allows', max_length=100),
        ),
    ]
